site_name: Bot on a Budget
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
plugins:
  - glightbox
  - social
copyright: Copyright &copy; 2025 Matthew Macdonald-Wallace (Proffalken)
